[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

    [buildPlans.iosevka-custom.variants.design]

    # Simplify letters.
    capital-g = "toothless-corner-serifless-hookless"
    capital-i = "short-serifed"
    capital-j = "serifless"
    capital-k = "symmetric-connected-serifless"
    capital-q = "straight"
    f = "flat-hook"
    g = "single-storey-flat-hook-serifless"
    k = "symmetric-connected-serifless"
    t = "flat-hook"

    # Make numbers beautiful.
    three = "flat-top"
    four = "semi-open-non-crossing"

    # Simplify special symbols.
    paren = "flat-arc"
    brace = "straight"
    dollar = "open"
    cent = "open"
    percent = "rings-continuous-slash"
    lig-ltgteq = "slanted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"


    [buildPlans.iosevka-custom.variants.italic]

    # Add tails.
    f = "flat-hook-tailed"
    h = "tailed"
    m = "tailed"
    n = "tailed"
    q = "tailed"

    # Make italic even more cursive.
    k = "diagonal-tailed-cursive-serifless"
    v = "cursive"
    w = "cursive"
    y = "cursive-flat-hook"
    z = "cursive"

  [buildPlans.iosevka-custom.ligations]
  inherits = "dlig"

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-custom.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-custom.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"